### ISSUE TITLE
Teleportation to the air.

### ISSUE THREAD

**Issue by KyleFreedomSeeds** [BrendonCurmi/FxBiomeRTP#15]
When doing /back (nucleus) right after teleporting to a biome, the player is teleported to their current coords (the place biomertp sent them), except at Y=900. No errors in console.

**Comment by BrendonCurmi** [comment]
Hi, yes because /back in Nucleus puts you back to where you were before the last teleportation. Biomertp works using 2 teleportations: first teleporting you to a random spot at Y=900 to be safe high in the sky for the server to generate and load the chunks, and then teleporting you safely on the ground. This happens because Sponge doesn't seem able to work out the safe ground distance without generating the chunks first. Will take a look later to see if it's possible to get the safe distance using other methods

**Comment by KyleFreedomSeeds** [comment]
See pull request
https://github.com/BrendonCurmi/FxBiomeRTP/pull/16

**Comment by BrendonCurmi** [comment]
Find the new version here: https://ore.spongepowered.org/FusionDev/FxBiomeRTP/versions/1.5
Thanks :)
